<?php
# AUTOGENERATED BY SALT - see puyonexus/salt on GitHub.
if (!defined('MEDIAWIKI')) { exit; }

# Extensions
{% for ext in salt["pillar.get"]("mediawiki:extensions") %}
wfLoadExtension('{{ ext }}');
{% endfor %}

# Setup CAPTCHA extension
wfLoadExtension('ConfirmEdit/QuestyCaptcha');
$wgCaptchaClass = 'QuestyCaptcha';
$wgCaptchaQuestions[] = array(
    'question' => 'What is the name (in English) of the protagonist\'s pet/sidekick in the video game Puyo Puyo?',
    'answer' => 'Carbuncle'
);
