<?php
# AUTOGENERATED BY SALT - see puyonexus/salt on GitHub.
if (!defined('MEDIAWIKI')) { exit; }

# Skins
{% for skin in salt["pillar.get"]("mediawiki:skins") %}
wfLoadSkin('{{ skin }}');
{% endfor %}

# Vector settings
$wgVectorUseSimpleSearch = true;
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgDefaultUserOptions['vector-collapsiblenav'] = 1;
